name: omise_dart
description: A Dart SDK that serves as an API wrapper for the Omise API.

version: 1.0.0
repository: https://github.com/omise/omise-dart

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
